//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27.08.2022 19:30:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace RadzenApp.Entities.QUVA
{
    public partial class FAHRZEUGE {

        public FAHRZEUGE()
        {
            this.KARTEN = new List<KARTEN>();
            OnCreated();
        }

        public virtual int FRZG_ID { get; set; }

        public virtual string TRANSPORTMITTEL { get; set; }

        public virtual string WERK_NR { get; set; }

        public virtual string SPEDITION { get; set; }

        public virtual double? TARA_GEWICHT { get; set; }

        public virtual DateTime? TARA_DATUM { get; set; }

        public virtual string REPLIKATION { get; set; }

        public virtual string ERFASST_VON { get; set; }

        public virtual DateTime? ERFASST_AM { get; set; }

        public virtual string ERFASST_DATENBANK { get; set; }

        public virtual string GEAENDERT_VON { get; set; }

        public virtual DateTime? GEAENDERT_AM { get; set; }

        public virtual string GEAENDERT_DATENBANK { get; set; }

        public virtual int? ANZAHL_AENDERUNGEN { get; set; }

        public virtual string BEMERKUNG { get; set; }

        public virtual string FAHRZEUGTYP { get; set; }

        public virtual int? TARA_FREI_ANZAHL { get; set; }

        public virtual double? MAX_BRUTTO { get; set; }

        public virtual string FLAGS { get; set; }

        public virtual int? SPED_ID { get; set; }

        public virtual IList<KARTEN> KARTEN { get; set; }

        public virtual SPEDITIONEN SPEDITIONEN { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
