//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02.06.2022 09:22:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace RadzenApp.Entities.QUVA
{
    /// <summary>
    /// snapshot query for snapshot QUVA.KARTEN
    /// </summary>
    public partial class KARTEN {

        public KARTEN()
        {
            this.KUND_KNZ = @"J";
            this.SPERR_KNZ = @"N";
            this.SPENDER_KNZ = @"N";
            this.SORTE_KNZ = @"N";
            this.FREMDWAEGUNG = @"N";
            this.PROBENPFLICHT = @"J";
            this.EINGANG_KNZ = @"N";
            this.KOMBI_KNZ = @"N";
            OnCreated();
        }

        public virtual int KART_ID { get; set; }

        public virtual string KART_NR { get; set; }

        public virtual string KUNW_NR { get; set; }

        public virtual string REPLIKATION { get; set; }

        public virtual string ERFASST_VON { get; set; }

        public virtual DateTime? ERFASST_AM { get; set; }

        public virtual string ERFASST_DATENBANK { get; set; }

        public virtual string GEAENDERT_VON { get; set; }

        public virtual DateTime? GEAENDERT_AM { get; set; }

        public virtual string GEAENDERT_DATENBANK { get; set; }

        public virtual int? ANZAHL_AENDERUNGEN { get; set; }

        public virtual string BEMERKUNG { get; set; }

        public virtual string WERK_NR { get; set; }

        public virtual string MARA_NR { get; set; }

        public virtual string TRANSPORTMITTEL { get; set; }

        public virtual string SPEDITION { get; set; }

        public virtual string AUFK_NR { get; set; }

        public virtual double? SOLLMENGE { get; set; }

        public virtual int? PEKR_ID { get; set; }

        public virtual string PEKR_NR { get; set; }

        public virtual string PEKR_BEZ { get; set; }

        public virtual string KUND_KNZ { get; set; }

        public virtual string SPERR_KNZ { get; set; }

        public virtual string SPENDER_KNZ { get; set; }

        public virtual int? SILO_NR { get; set; }

        public virtual string SORTE_KNZ { get; set; }

        public virtual string FREMDWAEGUNG { get; set; }

        public virtual double? TARA_GEWICHT { get; set; }

        public virtual DateTime? TARA_DATUM { get; set; }

        public virtual double? MAX_BRUTTO { get; set; }

        public virtual string TROCKEN_FEUCHT { get; set; }

        public virtual string PROBENPFLICHT { get; set; }

        public virtual double? TEILMENGE1 { get; set; }

        public virtual double? TEILMENGE2 { get; set; }

        public virtual double? TEILMENGE3 { get; set; }

        public virtual double? TEILMENGE4 { get; set; }

        public virtual double? TEILMENGE5 { get; set; }

        public virtual string ORI_KART_NR { get; set; }

        public virtual string EINGANG_KNZ { get; set; }

        public virtual string AUFBAU { get; set; }

        public virtual int? TARA_TAGE { get; set; }

        public virtual string KART_NR_2 { get; set; }

        public virtual string KOMBI_KNZ { get; set; }

        public virtual int? SPED_ID { get; set; }

        public virtual int? FRZG_ID { get; set; }

        public virtual SPEDITIONEN SPEDITIONEN { get; set; }

        public virtual FAHRZEUGE FAHRZEUGE { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
