//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02.06.2022 09:22:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace RadzenApp.Entities.QUVA
{
    public partial class SPEDITIONEN {

        public SPEDITIONEN()
        {
            this.PALETTENKONTO = @"N";
            this.KARTEN = new List<KARTEN>();
            this.FAHRZEUGE = new List<FAHRZEUGE>();
            OnCreated();
        }

        public virtual int SPED_ID { get; set; }

        public virtual string SPED_NAME { get; set; }

        public virtual string WERK_NR { get; set; }

        public virtual string REPLIKATION { get; set; }

        public virtual string ERFASST_VON { get; set; }

        public virtual DateTime? ERFASST_AM { get; set; }

        public virtual string ERFASST_DATENBANK { get; set; }

        public virtual string GEAENDERT_VON { get; set; }

        public virtual DateTime? GEAENDERT_AM { get; set; }

        public virtual string GEAENDERT_DATENBANK { get; set; }

        public virtual int? ANZAHL_AENDERUNGEN { get; set; }

        public virtual string BEMERKUNG { get; set; }

        public virtual string NAME_LANG { get; set; }

        public virtual string KREDITOR_NR { get; set; }

        public virtual string PALETTENKONTO { get; set; }

        /// <summary>
        /// Paletten Inventurdatum
        /// </summary>
        public virtual DateTime? PAL_INV_DTM { get; set; }

        /// <summary>
        /// Inventurbestand Euro-Paletten
        /// </summary>
        public virtual int? PAL_INV_BST_E { get; set; }

        /// <summary>
        /// Inventurbestand Düsseldorf-Paletten
        /// </summary>
        public virtual int? PAL_INV_BST_D { get; set; }

        public virtual IList<KARTEN> KARTEN { get; set; }

        public virtual IList<FAHRZEUGE> FAHRZEUGE { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
